install.packages("reticulate")
install.packages("Metrics")
install.packages("gridExtra")
install.packages("ggplot2")
install.packages("HDInterval")
install.packages("devtools")
devtools::install_github("GRousselet/rogme")
install.packages("tibble")
install.packages("stringi")
install.packages("epiR")
install.packages("rjson")
install.packages("viridis")
install.packages("lme4")
install.packages("irr")
install.packages("sjPlot")
install.packages("plotly")
install.packages("https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.6.0.tar.gz", repos=NULL, type="source")
install.packages("shiny")
install.packages("shinyjs")
install.packages("shinythemes")
install.packages("shinydashboard")

